import type MatBtn from './components/mat-btn/MatBtn.vue';
import type MatBtnGroup from './components/mat-btn-group/MatBtnGroup.vue';
import type MatFab from './components/mat-fab/MatFab.vue';
import type MatIcon from './components/mat-icon/MatIcon.vue';
import type MatSplitBtn from './components/mat-split-btn/MatSplitBtn.vue';
import type MatCard from './components/mat-card/MatCard.vue';
import type MatCardActionArea from './components/mat-card/MatCardActionArea.vue';
import type MatCardContent from './components/mat-card/MatCardContent.vue';
import type MatCardActions from './components/mat-card/MatCardActions.vue';
import type MatList from './components/mat-list/MatList.vue';
import type MatListGroup from './components/mat-list-group/MatListGroup.vue';
import type MatListItem from './components/mat-list/MatListItem.vue';
import type MatDivider from './components/mat-divider/MatDivider.vue';
import type MatCheckbox from './components/mat-checkbox/MatCheckbox.vue';
import type MatRadio from './components/mat-radio/MatRadio.vue';
import type MatRadioGroup from './components/mat-radio-group/MatRadioGroup.vue';
import type MatSwitch from './components/mat-switch/MatSwitch.vue';
import type MatSlider from './components/mat-slider/MatSlider.vue';
import type MatRangeSlider from './components/mat-range-slider/MatRangeSlider.vue';
import type MatTextField from './components/mat-text-field/MatTextField.vue';
import type MatTextarea from './components/mat-textarea/MatTextarea.vue';
import type MatInputBase from './components/MatInputBase.vue';
import type MatMenu from './components/mat-menu/MatMenu.vue';
import type MatMenuGroup from './components/mat-menu-group/MatMenuGroup.vue';
import type MatMenuItem from './components/mat-menu/MatMenuItem.vue';
import type MatDialog from './components/mat-dialog/MatDialog.vue';
import type MatHover from './components/mat-hover/MatHover.vue';
import type MatSpacer from './components/mat-spacer/MatSpacer.vue';
import type MatLoader from './components/mat-loader/MatLoader.vue';
import type MatTooltip from './components/mat-tooltip/MatTooltip.vue';
import type MatSnackbar from './components/mat-snackbar/MatSnackbar.vue';
import type MatToolbar from './components/mat-toolbar/MatToolbar.vue';
import type MatPanes from './components/mat-panes/MatPanes.vue';
import type MatPane from './components/mat-panes/MatPane.vue';
import type MatNavigationRail from './components/mat-navigation-rail/MatNavigationRail.vue';
import type MatNavigationRailItem from './components/mat-navigation-rail/MatNavigationRailItem.vue';

export { default as MatBtn } from './components/mat-btn/MatBtn.vue';
export { default as MatBtnGroup } from './components/mat-btn-group/MatBtnGroup.vue';
export { default as MatFab } from './components/mat-fab/MatFab.vue';
export { default as MatIcon } from './components/mat-icon/MatIcon.vue';
export { default as MatSplitBtn } from './components/mat-split-btn/MatSplitBtn.vue';
export { default as MatCard } from './components/mat-card/MatCard.vue';
export { default as MatCardActionArea } from './components/mat-card/MatCardActionArea.vue';
export { default as MatCardContent } from './components/mat-card/MatCardContent.vue';
export { default as MatCardActions } from './components/mat-card/MatCardActions.vue';
export { default as MatList } from './components/mat-list/MatList.vue';
export { default as MatListGroup } from './components/mat-list-group/MatListGroup.vue';
export { default as MatListItem } from './components/mat-list/MatListItem.vue';
export { default as MatDivider } from './components/mat-divider/MatDivider.vue';
export { default as MatCheckbox } from './components/mat-checkbox/MatCheckbox.vue';
export { default as MatRadio } from './components/mat-radio/MatRadio.vue';
export { default as MatRadioGroup } from './components/mat-radio-group/MatRadioGroup.vue';
export { default as MatSwitch } from './components/mat-switch/MatSwitch.vue';
export { default as MatSlider } from './components/mat-slider/MatSlider.vue';
export { default as MatRangeSlider } from './components/mat-range-slider/MatRangeSlider.vue';
export { default as MatTextField } from './components/mat-text-field/MatTextField.vue';
export { default as MatTextarea } from './components/mat-textarea/MatTextarea.vue';
export { default as MatInputBase } from './components/MatInputBase.vue';
export { default as MatMenu } from './components/mat-menu/MatMenu.vue';
export { default as MatMenuGroup } from './components/mat-menu-group/MatMenuGroup.vue';
export { default as MatMenuItem } from './components/mat-menu/MatMenuItem.vue';
export { default as MatDialog } from './components/mat-dialog/MatDialog.vue';
export { default as MatHover } from './components/mat-hover/MatHover.vue';
export { default as MatSpacer } from './components/mat-spacer/MatSpacer.vue';
export { default as MatLoader } from './components/mat-loader/MatLoader.vue';
export { default as MatTooltip } from './components/mat-tooltip/MatTooltip.vue';
export { default as MatSnackbar } from './components/mat-snackbar/MatSnackbar.vue';
export { default as MatToolbar } from './components/mat-toolbar/MatToolbar.vue';
export { default as MatPanes } from './components/mat-panes/MatPanes.vue';
export { default as MatPane } from './components/mat-panes/MatPane.vue';
export { default as MatNavigationRail } from './components/mat-navigation-rail/MatNavigationRail.vue';
export { default as MatNavigationRailItem } from './components/mat-navigation-rail/MatNavigationRailItem.vue';
export { default as Intersection } from './directives/intersection';
export { createMatUi, useMatTheme } from './plugin.js';

declare module 'vue' {
  export interface GlobalComponents {
    MatBtn: typeof MatBtn;
    'mat-btn': typeof MatBtn;
    MatBtnGroup: typeof MatBtnGroup;
    'mat-btn-group': typeof MatBtnGroup;
    MatFab: typeof MatFab;
    'mat-fab': typeof MatFab;
    MatIcon: typeof MatIcon;
    'mat-icon': typeof MatIcon;
    MatSplitBtn: typeof MatSplitBtn;
    'mat-split-btn': typeof MatSplitBtn;
    MatCard: typeof MatCard;
    'mat-card': typeof MatCard;
    MatCardActionArea: typeof MatCardActionArea;
    'mat-card-action-area': typeof MatCardActionArea;
    MatCardContent: typeof MatCardContent;
    'mat-card-content': typeof MatCardContent;
    MatCardActions: typeof MatCardActions;
    'mat-card-actions': typeof MatCardActions;
    MatList: typeof MatList;
    'mat-list': typeof MatList;
    MatListGroup: typeof MatListGroup;
    'mat-list-group': typeof MatListGroup;
    MatListItem: typeof MatListItem;
    'mat-list-item': typeof MatListItem;
    MatDivider: typeof MatDivider;
    'mat-divider': typeof MatDivider;
    MatCheckbox: typeof MatCheckbox;
    'mat-checkbox': typeof MatCheckbox;
    MatRadio: typeof MatRadio;
    'mat-radio': typeof MatRadio;
    MatRadioGroup: typeof MatRadioGroup;
    'mat-radio-group': typeof MatRadioGroup;
    MatSwitch: typeof MatSwitch;
    'mat-switch': typeof MatSwitch;
    MatSlider: typeof MatSlider;
    'mat-slider': typeof MatSlider;
    MatRangeSlider: typeof MatRangeSlider;
    'mat-range-slider': typeof MatRangeSlider;
    MatTextField: typeof MatTextField;
    'mat-text-field': typeof MatTextField;
    MatTextarea: typeof MatTextarea;
    'mat-textarea': typeof MatTextarea;
    MatInputBase: typeof MatInputBase;
    'mat-input-base': typeof MatInputBase;
    MatMenu: typeof MatMenu;
    'mat-menu': typeof MatMenu;
    MatMenuGroup: typeof MatMenuGroup;
    'mat-menu-group': typeof MatMenuGroup;
    MatMenuItem: typeof MatMenuItem;
    'mat-menu-item': typeof MatMenuItem;
    MatDialog: typeof MatDialog;
    'mat-dialog': typeof MatDialog;
    MatHover: typeof MatHover;
    'mat-hover': typeof MatHover;
    MatSpacer: typeof MatSpacer;
    'mat-spacer': typeof MatSpacer;
    MatLoader: typeof MatLoader;
    'mat-loader': typeof MatLoader;
    MatTooltip: typeof MatTooltip;
    'mat-tooltip': typeof MatTooltip;
    MatSnackbar: typeof MatSnackbar;
    'mat-snackbar': typeof MatSnackbar;
    MatToolbar: typeof MatToolbar;
    'mat-toolbar': typeof MatToolbar;
    MatPanes: typeof MatPanes;
    'mat-panes': typeof MatPanes;
    MatPane: typeof MatPane;
    'mat-pane': typeof MatPane;
    MatNavigationRail: typeof MatNavigationRail;
    'mat-navigation-rail': typeof MatNavigationRail;
    MatNavigationRailItem: typeof MatNavigationRailItem;
    'mat-navigation-rail-item': typeof MatNavigationRailItem;
  }
}
