export { default as MatBtn } from './components/mat-btn/MatBtn.vue';
export { default as MatAppRoot } from './components/mat-app-root/MatAppRoot.vue';
export { default as MatAppBar } from './components/mat-app-bar/MatAppBar.vue';
export { default as MatSearch } from './components/mat-search/MatSearch.vue';
export { default as MatBtnGroup } from './components/mat-btn-group/MatBtnGroup.vue';
export { default as MatFab } from './components/mat-fab/MatFab.vue';
export { default as MatFabMenu } from './components/mat-fab-menu/MatFabMenu.vue';
export { default as MatIcon } from './components/mat-icon/MatIcon.vue';
export { default as MatImage } from './components/mat-image/MatImage.vue';
export { default as MatSharedElement } from './components/mat-shared-element/MatSharedElement.vue';
export { default as MdeSharedElement } from './components/mat-shared-element/MatSharedElement.vue';
export { default as MatAvatar } from './components/mat-avatar/MatAvatar.vue';
export { default as MatShape } from './components/mat-shape/MatShape.vue';
export { default as MatText } from './components/mat-text/MatText.vue';
export { default as MatDynamicText } from './components/mat-dynamic-text/MatDynamicText.vue';
export { default as MatSplitBtn } from './components/mat-split-btn/MatSplitBtn.vue';
export { default as MatCard } from './components/mat-card/MatCard.vue';
export { default as MatCardActionArea } from './components/mat-card/MatCardActionArea.vue';
export { default as MatCardContent } from './components/mat-card/MatCardContent.vue';
export { default as MatCardActions } from './components/mat-card/MatCardActions.vue';
export { default as MatCardHeadline } from './components/mat-card/MatCardHeadline.vue';
export { default as MatCardSubhead } from './components/mat-card/MatCardSubhead.vue';
export { default as MatCardMedia } from './components/mat-card/MatCardMedia.vue';
export { default as MatExpansion } from './components/mat-expansion/MatExpansion.vue';
export { default as MatExpansionPanel } from './components/mat-expansion/MatExpansionPanel.vue';
export { default as MatList } from './components/mat-list/MatList.vue';
export { default as MatListGroup } from './components/mat-list-group/MatListGroup.vue';
export { default as MatListItem } from './components/mat-list/MatListItem.vue';
export { default as MatDivider } from './components/mat-divider/MatDivider.vue';
export { default as MatCheckbox } from './components/mat-checkbox/MatCheckbox.vue';
export { default as MatBadge } from './components/mat-badge/MatBadge.vue';
export { default as MatChip } from './components/mat-chip/MatChip.vue';
export { default as MatChipSet } from './components/mat-chip/MatChipSet.vue';
export { default as MatRadio } from './components/mat-radio/MatRadio.vue';
export { default as MatRadioGroup } from './components/mat-radio-group/MatRadioGroup.vue';
export { default as MatSwitch } from './components/mat-switch/MatSwitch.vue';
export { default as MatSlider } from './components/mat-slider/MatSlider.vue';
export { default as MatRangeSlider } from './components/mat-range-slider/MatRangeSlider.vue';
export { default as MatTextField } from './components/mat-text-field/MatTextField.vue';
export { default as MatSelect } from './components/mat-select/MatSelect.vue';
export { default as MatTextarea } from './components/mat-textarea/MatTextarea.vue';
export { default as MatInputBase } from './components/MatInputBase.vue';
export { default as MatMenu } from './components/mat-menu/MatMenu.vue';
export { default as MatMenuGroup } from './components/mat-menu-group/MatMenuGroup.vue';
export { default as MatMenuItem } from './components/mat-menu/MatMenuItem.vue';
export { default as MatDockedContainer } from './components/mat-docked-container/MatDockedContainer.vue';
export { default as MatDialog } from './components/mat-dialog/MatDialog.vue';
export { default as MatBottomSheet } from './components/mat-bottom-sheet/MatBottomSheet.vue';
export { default as MatSideSheet } from './components/mat-side-sheet/MatSideSheet.vue';
export { default as MatHover } from './components/mat-hover/MatHover.vue';
export { default as MatContainer } from './components/mat-container/MatContainer.vue';
export { default as MatSpacer } from './components/mat-spacer/MatSpacer.vue';
export { default as MatTableWrapper } from './components/mat-table-wrapper/MatTableWrapper.vue';
export { default as MatScrollArea } from './components/mat-scroll-area/MatScrollArea.vue';
export { default as MatVirtualScroll } from './components/mat-virtual-scroll/MatVirtualScroll.vue';
export { default as MdeVirtualScroll } from './components/mat-virtual-scroll/MatVirtualScroll.vue';
export { default as MatLoading } from './components/mat-loading/MatLoading.vue';
export { default as MatPullToRefresh } from './components/mat-pull-to-refresh/MatPullToRefresh.vue';
export { default as MatProgress } from './components/mat-progress/MatProgress.vue';
export { default as MatTooltip } from './components/mat-tooltip/MatTooltip.vue';
export { default as MatSnackbar } from './components/mat-snackbar/MatSnackbar.vue';
export { default as MatToolbar } from './components/mat-toolbar/MatToolbar.vue';
export { default as MatPanes } from './components/mat-panes/MatPanes.vue';
export { default as MatPane } from './components/mat-panes/MatPane.vue';
export { default as MatNavigationRail } from './components/mat-navigation-rail/MatNavigationRail.vue';
export { default as MatNavigationRailItem } from './components/mat-navigation-rail/MatNavigationRailItem.vue';
export { default as Intersection } from './directives/intersection';
export { default as StateLayer } from './directives/state-layer';
// Node/Vitest 直接解析包源码时需要保留 JavaScript 扩展名。
// eslint-disable-next-line import-x/extensions
export { createMatUi, useMatTheme } from './plugin.js';
// eslint-disable-next-line import-x/extensions
export { useMatProps } from './components/use-mat-props.js';
// eslint-disable-next-line import-x/extensions
export { useMatViewTransition, useMdeViewTransition } from './view-transition.js';
export { useMatApp } from './components/mat-app-root/mat-app-root-context';
export {
  alert, confirm, dialog, prompt,
} from './components/mat-dialog/dialog';
export { snackbar, toast } from './components/mat-snackbar/snackbar';
